name = "MakieTreeMaps"
uuid = "ae27a423-219c-4596-bb2b-dd8a6aaf3b5b"
authors = ["Julius Krumbiegel <julius.krumbiegel@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
